#include "../include/headerA3.h"

void recruitEmployee (struct employee ** headLL) {
  a3Emp * empArr = malloc(sizeof(a3Emp)*1); //initial dynamic allocation

  //asking user for their full names
  printf("Enter the first name of the employee: ");
  scanf("%s", empArr->fname);
  printf("Enter the last name of the employee: ");
  scanf("%s", empArr->lname);

  //asking user for dependents
  char moreDep = 'y';
  int num = 0;
  a3Emp * temp = *headLL;
  empArr->dependents = NULL;
  while (moreDep == 'y' || moreDep == 'Y') { //while loop to dynamically allocate space for the names of the dependents
    printf("Enter the name of dependent #%d: ", (num+1));

    if (empArr->dependents == NULL) { //first node of the LL
      empArr->dependents = malloc(sizeof(char *) * 1);
    }
    else { //all other nodes
       empArr->dependents = realloc(empArr->dependents, sizeof(char *)*(num+1));
    }

    //inputting for the name of the depedents
    empArr->dependents[num] = malloc(sizeof(char) * MAX_LENGTH);
    scanf("%s", empArr->dependents[num]);
    printf("this is the dependent at index %d ", (num+1));
    printf("\n%s \n", empArr->dependents[num]);
    num++;

    //asking if there are anymore dependents
    printf("\nDo you have any more dependents? (y/n): ");
    scanf("%c ", &moreDep);
    moreDep = getchar();
    printf("\nmoreDep is %c\n", moreDep);
  }

  //counting how many dependents there are from counter variable
  empArr->numDependents = num;
  printf("You have (%d) dependent(s).\n", num);

  for(int i = 0; i < empArr->numDependents+1; i++) {
    //printf("For loop \n");
    if (empArr->dependents[i] == NULL) {
      //printf("In While loop?\n");
      free(empArr->dependents[i]);
    }
  }

  //generating employee's ID with ascii values or random numbers
  int totalAscii = 0;
  int asciiVal = 0;
  int lnameLen = strlen(empArr->lname);
  for (int i = 0; i < strlen(empArr->fname); i++){
    asciiVal = (int)(empArr->fname[i]); //generating ascii values because e.g int value = "a"; would make value = 65.
    totalAscii = totalAscii + asciiVal;
  }
  empArr->empId = totalAscii + lnameLen;
  empArr->nextEmployee = NULL;
  while (temp != NULL){
    if (temp->empId == empArr->empId){
      empArr->empId = empArr->empId + (rand() % 999);
    }
    temp = temp->nextEmployee;
  }

  if (*headLL == NULL) { //testing if LL is empty
    *headLL = empArr;
    return;
  }

  printf("Your computer-generated name empID is %d.\n", empArr->empId); // print Employee ID generated by computer

  temp = *headLL;

  while (temp != NULL) {
    if (temp->nextEmployee == NULL) { //moving to the next employee in the LL
        temp->nextEmployee = empArr;
        return;
    }
    //printf("go ");
    temp = temp->nextEmployee;
  }

  printf("End of function 1");
}

//wtf why is this not working
//Max is my homie he gave me a regrade <3

